GET http://localhost:3000/

### findAll() method
GET http://localhost:3000/songs?page=1&limit=10

### findOne() method
GET http://localhost:3000/songs/2

### create() method
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Pink Moon",
    "artists": [2],
    "album": "Pink Moon - Single",
    "releaseDate": "1972-01-01",
    "duration": "05:04",
    "lyrics": "Pink Moon is a song by Nick Drake. He wrote the lyrics."
}

### update() method
PUT http://localhost:3000/songs/1

### delete() method 
DELETE http://localhost:3000/songs/1   

### create playlist
POST http://localhost:3000/playlist
Content-Type: application/json

{
    "name": "Sids Playlist",
    "songIds": [2, 3, 4, 5, 6, 7],
    "user": 1
}

### findAll playlists
GET http://localhost:3000/playlist

### findOne playlist
GET http://localhost:3000/playlist/1 

### delete playlist
DELETE http://localhost:3000/playlist/1