GET http://localhost:3000/

### findAll() method
GET http://localhost:3000/song?page=1&limit=10

### findOne() method
GET http://localhost:3000/song/2

### create() method
POST http://localhost:3000/song
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWVAZ21haWwuY29tIiwidXNlcklkIjo3LCJpYXQiOjE3NTMwNDcwMDcsImV4cCI6MTc1MzA1MDYwN30.pSRYDRDALyhOm7wPx_mQfT8MMtMMDv8FHK-k0UX3r_4

{
    "title": "Some Song",
    "artists": [7],
    "album": "Some Song - Single",
    "releaseDate": "2025-01-01",
    "duration": "05:04",
    "lyrics": "Some Song is a song by Some User. He wrote the lyrics."
}

### update() method
PUT http://localhost:3000/song/1

### delete() method 
DELETE http://localhost:3000/song/11

### create playlist
POST http://localhost:3000/playlist
Content-Type: application/json

{
    "name": "Sids Playlist",
    "songIds": [2, 3, 4, 5, 6, 7],
    "user": 1
}

### findAll playlists
GET http://localhost:3000/playlist

### findOne playlist
GET http://localhost:3000/playlist/3

### delete playlist
DELETE http://localhost:3000/playlist/1

### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Some",
    "lastName": "User",
    "email": "some@gmail.com",
    "password": "123456"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "sid@gmail.com",
    "password": "123456"
}

### create artist
POST http://localhost:3000/artist
Content-Type: application/json

{
    "name": "Some Artist"
}


### profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpZEBnbWFpbC5jb20iLCJ1c2VySWQiOjQsImlhdCI6MTc1MzA2NDg4MCwiZXhwIjoxNzUzMDY4NDgwfQ.N1lr3XFMTUePpDjH-kG6eeuccqK2RcNtGorlm7seO6w
//Access token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpbEBnbWFpbC5jb20iLCJ1c2VySWQiOjYsImlhdCI6MTc1MzA0NTM4NSwiZXhwIjoxNzUzMDQ4OTg1fQ.siu3IoTf9zFjd48YAQeaCzwngmi5E43t60JBV2diK00

### enable two fa
GET http://localhost:3000/auth/enable-two-fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpZEBnbWFpbC5jb20iLCJ1c2VySWQiOjQsImlhdCI6MTc1MzA2NjQ2NSwiZXhwIjoxNzUzMDcwMDY1fQ.NHxKpd5eU7idfsqeFqquaGIb9H0tS_AEBWz59TfaMcM

### verify two fa
POST http://localhost:3000/auth/verify-two-fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpZEBnbWFpbC5jb20iLCJ1c2VySWQiOjQsImlhdCI6MTc1MzA2MzM2MCwiZXhwIjoxNzUzMDY2OTYwfQ.ciRGUhdx5-h7-5jEXF3P3KmzsGLHssD065ewm7KCHzw

{
    "token": "720938"
}

### disable two fa
POST http://localhost:3000/auth/disable-two-fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpZEBnbWFpbC5jb20iLCJ1c2VySWQiOjQsImlhdCI6MTc1MzA2MzM2MCwiZXhwIjoxNzUzMDY2OTYwfQ.ciRGUhdx5-h7-5jEXF3P3KmzsGLHssD065ewm7KCHzw


//Secret for Sid user: KRRE42LUJ4ZES5CHJ5CVUL26OUTF4SK5G5AG6PDYHZYDQ2LBFZXA